# coding: utf-8

# flake8: noqa

"""
    BAHMS Poker Tournament

    # Error Format & Meaning  All response messages are in the format of: ```json {   \"message_type\": \"string\",   \"data\": {} } ```  All errors use the \"error\" message_type and have the data format of: ```json {   \"error_code\": int,   \"error\": \"string\" } ```   The \"error\" field is intended only as a human readable message and should not be depended on for branching or parsing in code. This field should be considered volatile within the api. The error_code field is stable and intended for client code to use within recovery operations. The error codes and their meanings are enumerated in the table below   |   Code | Name                  | Meaning                                       | | -----: | --------------------- | --------------------------------------------- | | `1000` | `Unknown` | A novel error...congrats.                | | `1001` | `TurnOrderViolation`     | Player action received for a player out of turn. | | `1002` | `InvalidActionType`   | Player action received with an intent that is not valid for the game state.                        | | `1003` | `NotEnoughChips`   | Player action received with a chip amount that cannot be covered by the players stack            | | `1004` | `InvalidBetAmount`    | Player action received with a bet amount that violates requirements i.e. incorrect amount for a blind, call, or a raise which is too low.                 |   

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AdminApi",
    "GameApi",
    "UserApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AdminGameStatus",
    "AdminGameStatusDTO",
    "GameActiveGameDTO",
    "GameCardDTO",
    "GameChipExchangeDTO",
    "GameGameDTO",
    "GameHandDTO",
    "GameNewGameConfigDTO",
    "GameNewHandDTO",
    "GamePlayerActionDTO",
    "GamePlayerDTO",
    "GamePlayerIntent",
    "GameRoundDTO",
    "GameRoundType",
    "GameTableDTO",
    "JustErrorCode",
    "JustErrorDTO",
    "JustHandEvaluationDTO",
    "JustResponseMessageAny",
    "JustResponseMessageGameGameDTO",
    "JustResponseMessageJustErrorDTO",
    "JustResponseMessageString",
    "JustUserType",
]

# import apis into sdk package
from openapi_client.api.admin_api import AdminApi as AdminApi
from openapi_client.api.game_api import GameApi as GameApi
from openapi_client.api.user_api import UserApi as UserApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.admin_game_status import AdminGameStatus as AdminGameStatus
from openapi_client.models.admin_game_status_dto import AdminGameStatusDTO as AdminGameStatusDTO
from openapi_client.models.game_active_game_dto import GameActiveGameDTO as GameActiveGameDTO
from openapi_client.models.game_card_dto import GameCardDTO as GameCardDTO
from openapi_client.models.game_chip_exchange_dto import GameChipExchangeDTO as GameChipExchangeDTO
from openapi_client.models.game_game_dto import GameGameDTO as GameGameDTO
from openapi_client.models.game_hand_dto import GameHandDTO as GameHandDTO
from openapi_client.models.game_new_game_config_dto import GameNewGameConfigDTO as GameNewGameConfigDTO
from openapi_client.models.game_new_hand_dto import GameNewHandDTO as GameNewHandDTO
from openapi_client.models.game_player_action_dto import GamePlayerActionDTO as GamePlayerActionDTO
from openapi_client.models.game_player_dto import GamePlayerDTO as GamePlayerDTO
from openapi_client.models.game_player_intent import GamePlayerIntent as GamePlayerIntent
from openapi_client.models.game_round_dto import GameRoundDTO as GameRoundDTO
from openapi_client.models.game_round_type import GameRoundType as GameRoundType
from openapi_client.models.game_table_dto import GameTableDTO as GameTableDTO
from openapi_client.models.just_error_code import JustErrorCode as JustErrorCode
from openapi_client.models.just_error_dto import JustErrorDTO as JustErrorDTO
from openapi_client.models.just_hand_evaluation_dto import JustHandEvaluationDTO as JustHandEvaluationDTO
from openapi_client.models.just_response_message_any import JustResponseMessageAny as JustResponseMessageAny
from openapi_client.models.just_response_message_game_game_dto import JustResponseMessageGameGameDTO as JustResponseMessageGameGameDTO
from openapi_client.models.just_response_message_just_error_dto import JustResponseMessageJustErrorDTO as JustResponseMessageJustErrorDTO
from openapi_client.models.just_response_message_string import JustResponseMessageString as JustResponseMessageString
from openapi_client.models.just_user_type import JustUserType as JustUserType

