[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "poker-bot-sdk"
version = "0.1.0"

[project.scripts]
poker-tui = "poker_bot.tools.tui.__main__:main"
new-game = "poker_bot.tools.create_game.__main__:main"
join-game = "poker_bot.tools.join_game.__main__:main"
listen-game = "poker_bot.tools.listen_game.__main__:main"
start-game = "poker_bot.tools.start_game.__main__:main"
get-game = "poker_bot.tools.game_state.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["poker_bot*", "openapi_client*"]

[tool.pyright]
typeCheckingMode = "off"
ignore = ["src/openapi_client"]

[tool.ruff]
extend-exclude = ["src/openapi_client"]

[tool.ruff.lint]
extend-select = ["I"]
