[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "poker-bot-sdk"
version = "0.1.0"

[project.scripts]
poker-tui = "just.tui.__main__:main"
new-game = "just.create_game.__main__:main"
join-game = "just.join_game.__main__:main"
listen-game = "just.listen_game.__main__:main"
start-game = "just.start_game.__main__:main"
get-game = "just.game_state.__main__:main"
jamble-bot = "examples.jambler.__main__:main"

[tool.setuptools.packages.find]
where = ["src", "examples"]
include = ["poker_bot*", "openapi_client*", "just*"]

[tool.pyright]
typeCheckingMode = "off"
ignore = ["src/openapi_client"]

[tool.ruff]
extend-exclude = ["src/openapi_client"]
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]
