# coding: utf-8

# flake8: noqa
"""
    BAHMS Poker Tournament

    # Error Format & Meaning  All response messages are in the format of: ```json {   \"message_type\": \"string\",   \"data\": {} } ```  All errors use the \"error\" message_type and have the data format of: ```json {   \"error_code\": int,   \"error\": \"string\" } ```   The \"error\" field is intended only as a human readable message and should not be depended on for branching or parsing in code. This field should be considered volatile within the api. The error_code field is stable and intended for client code to use within recovery operations. The error codes and their meanings are enumerated in the table below   |   Code | Name                  | Meaning                                       | | -----: | --------------------- | --------------------------------------------- | | `1000` | `Unknown` | A novel error...congrats.                | | `1001` | `TurnOrderViolation`     | Player action received for a player out of turn. | | `1002` | `InvalidActionType`   | Player action received with an intent that is not valid for the game state.                        | | `1003` | `NotEnoughChips`   | Player action received with a chip amount that cannot be covered by the players stack            | | `1004` | `InvalidBetAmount`    | Player action received with a bet amount that violates requirements i.e. incorrect amount for a blind, call, or a raise which is too low.                 |   

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.admin_game_game_id_status_post_request import AdminGameGameIdStatusPostRequest
from openapi_client.models.admin_game_game_id_table_post_request import AdminGameGameIdTablePostRequest
from openapi_client.models.admin_game_status import AdminGameStatus
from openapi_client.models.admin_game_status_dto import AdminGameStatusDTO
from openapi_client.models.game_active_game_dto import GameActiveGameDTO
from openapi_client.models.game_card_dto import GameCardDTO
from openapi_client.models.game_chip_exchange_dto import GameChipExchangeDTO
from openapi_client.models.game_game_dto import GameGameDTO
from openapi_client.models.game_game_id_action_post_request import GameGameIdActionPostRequest
from openapi_client.models.game_game_id_chip_exchange_post_request import GameGameIdChipExchangePostRequest
from openapi_client.models.game_hand_dto import GameHandDTO
from openapi_client.models.game_new_game_config_dto import GameNewGameConfigDTO
from openapi_client.models.game_player_action_dto import GamePlayerActionDTO
from openapi_client.models.game_player_dto import GamePlayerDTO
from openapi_client.models.game_post_request import GamePostRequest
from openapi_client.models.game_round_dto import GameRoundDTO
from openapi_client.models.game_round_type import GameRoundType
from openapi_client.models.game_table_dto import GameTableDTO
from openapi_client.models.hand_evaluator_evaluate_post_request import HandEvaluatorEvaluatePostRequest
from openapi_client.models.just_error_dto import JustErrorDTO
from openapi_client.models.just_response_message_any import JustResponseMessageAny
from openapi_client.models.just_response_message_game_game_dto import JustResponseMessageGameGameDTO
from openapi_client.models.just_response_message_just_error_dto import JustResponseMessageJustErrorDTO
from openapi_client.models.just_response_message_string import JustResponseMessageString
from openapi_client.models.just_user_type import JustUserType

