# coding: utf-8

"""
    BAHMS Poker Tournament

    # Error Format & Meaning  All response messages are in the format of: ```json {   \"message_type\": \"string\",   \"data\": {} } ```  All errors use the \"error\" message_type and have the data format of: ```json {   \"error_code\": int,   \"error\": \"string\" } ```   The \"error\" field is intended only as a human readable message and should not be depended on for branching or parsing in code. This field should be considered volatile within the api. The error_code field is stable and intended for client code to use within recovery operations. The error codes and their meanings are enumerated in the table below   |   Code | Name                  | Meaning                                       | | -----: | --------------------- | --------------------------------------------- | | `1000` | `Unknown` | A novel error...congrats.                | | `1001` | `TurnOrderViolation`     | Player action received for a player out of turn. | | `1002` | `InvalidActionType`   | Player action received with an intent that is not valid for the game state.                        | | `1003` | `NotEnoughChips`   | Player action received with a chip amount that cannot be covered by the players stack            | | `1004` | `InvalidBetAmount`    | Player action received with a bet amount that violates requirements i.e. incorrect amount for a blind, call, or a raise which is too low.                 |   

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.just_websocket_message_array_game_payout_event_dto import JustWebsocketMessageArrayGamePayoutEventDTO
from openapi_client.models.just_websocket_message_game_chip_exchange_dto import JustWebsocketMessageGameChipExchangeDTO
from openapi_client.models.just_websocket_message_game_game_dto import JustWebsocketMessageGameGameDTO
from openapi_client.models.just_websocket_message_game_hand_start_event_dto import JustWebsocketMessageGameHandStartEventDTO
from openapi_client.models.just_websocket_message_game_player_action_dto import JustWebsocketMessageGamePlayerActionDTO
from openapi_client.models.just_websocket_message_game_round_start_event_dto import JustWebsocketMessageGameRoundStartEventDTO
from openapi_client.models.just_websocket_message_game_turn_start_event_dto import JustWebsocketMessageGameTurnStartEventDTO
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

GAMEGAMEIDSTATELISTENGET200RESPONSE_ONE_OF_SCHEMAS = ["JustWebsocketMessageArrayGamePayoutEventDTO", "JustWebsocketMessageGameChipExchangeDTO", "JustWebsocketMessageGameGameDTO", "JustWebsocketMessageGameHandStartEventDTO", "JustWebsocketMessageGamePlayerActionDTO", "JustWebsocketMessageGameRoundStartEventDTO", "JustWebsocketMessageGameTurnStartEventDTO"]

class GameGameIdStateListenGet200Response(BaseModel):
    """
    GameGameIdStateListenGet200Response
    """
    # data type: JustWebsocketMessageGameRoundStartEventDTO
    oneof_schema_1_validator: Optional[JustWebsocketMessageGameRoundStartEventDTO] = None
    # data type: JustWebsocketMessageGameHandStartEventDTO
    oneof_schema_2_validator: Optional[JustWebsocketMessageGameHandStartEventDTO] = None
    # data type: JustWebsocketMessageGameGameDTO
    oneof_schema_3_validator: Optional[JustWebsocketMessageGameGameDTO] = None
    # data type: JustWebsocketMessageArrayGamePayoutEventDTO
    oneof_schema_4_validator: Optional[JustWebsocketMessageArrayGamePayoutEventDTO] = None
    # data type: JustWebsocketMessageGamePlayerActionDTO
    oneof_schema_5_validator: Optional[JustWebsocketMessageGamePlayerActionDTO] = None
    # data type: JustWebsocketMessageGameTurnStartEventDTO
    oneof_schema_6_validator: Optional[JustWebsocketMessageGameTurnStartEventDTO] = None
    # data type: JustWebsocketMessageGameChipExchangeDTO
    oneof_schema_7_validator: Optional[JustWebsocketMessageGameChipExchangeDTO] = None
    actual_instance: Optional[Union[JustWebsocketMessageArrayGamePayoutEventDTO, JustWebsocketMessageGameChipExchangeDTO, JustWebsocketMessageGameGameDTO, JustWebsocketMessageGameHandStartEventDTO, JustWebsocketMessageGamePlayerActionDTO, JustWebsocketMessageGameRoundStartEventDTO, JustWebsocketMessageGameTurnStartEventDTO]] = None
    one_of_schemas: Set[str] = { "JustWebsocketMessageArrayGamePayoutEventDTO", "JustWebsocketMessageGameChipExchangeDTO", "JustWebsocketMessageGameGameDTO", "JustWebsocketMessageGameHandStartEventDTO", "JustWebsocketMessageGamePlayerActionDTO", "JustWebsocketMessageGameRoundStartEventDTO", "JustWebsocketMessageGameTurnStartEventDTO" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = GameGameIdStateListenGet200Response.model_construct()
        error_messages = []
        match = 0
        # validate data type: JustWebsocketMessageGameRoundStartEventDTO
        if not isinstance(v, JustWebsocketMessageGameRoundStartEventDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `JustWebsocketMessageGameRoundStartEventDTO`")
        else:
            match += 1
        # validate data type: JustWebsocketMessageGameHandStartEventDTO
        if not isinstance(v, JustWebsocketMessageGameHandStartEventDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `JustWebsocketMessageGameHandStartEventDTO`")
        else:
            match += 1
        # validate data type: JustWebsocketMessageGameGameDTO
        if not isinstance(v, JustWebsocketMessageGameGameDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `JustWebsocketMessageGameGameDTO`")
        else:
            match += 1
        # validate data type: JustWebsocketMessageArrayGamePayoutEventDTO
        if not isinstance(v, JustWebsocketMessageArrayGamePayoutEventDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `JustWebsocketMessageArrayGamePayoutEventDTO`")
        else:
            match += 1
        # validate data type: JustWebsocketMessageGamePlayerActionDTO
        if not isinstance(v, JustWebsocketMessageGamePlayerActionDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `JustWebsocketMessageGamePlayerActionDTO`")
        else:
            match += 1
        # validate data type: JustWebsocketMessageGameTurnStartEventDTO
        if not isinstance(v, JustWebsocketMessageGameTurnStartEventDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `JustWebsocketMessageGameTurnStartEventDTO`")
        else:
            match += 1
        # validate data type: JustWebsocketMessageGameChipExchangeDTO
        if not isinstance(v, JustWebsocketMessageGameChipExchangeDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `JustWebsocketMessageGameChipExchangeDTO`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in GameGameIdStateListenGet200Response with oneOf schemas: JustWebsocketMessageArrayGamePayoutEventDTO, JustWebsocketMessageGameChipExchangeDTO, JustWebsocketMessageGameGameDTO, JustWebsocketMessageGameHandStartEventDTO, JustWebsocketMessageGamePlayerActionDTO, JustWebsocketMessageGameRoundStartEventDTO, JustWebsocketMessageGameTurnStartEventDTO. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in GameGameIdStateListenGet200Response with oneOf schemas: JustWebsocketMessageArrayGamePayoutEventDTO, JustWebsocketMessageGameChipExchangeDTO, JustWebsocketMessageGameGameDTO, JustWebsocketMessageGameHandStartEventDTO, JustWebsocketMessageGamePlayerActionDTO, JustWebsocketMessageGameRoundStartEventDTO, JustWebsocketMessageGameTurnStartEventDTO. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into JustWebsocketMessageGameRoundStartEventDTO
        try:
            instance.actual_instance = JustWebsocketMessageGameRoundStartEventDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into JustWebsocketMessageGameHandStartEventDTO
        try:
            instance.actual_instance = JustWebsocketMessageGameHandStartEventDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into JustWebsocketMessageGameGameDTO
        try:
            instance.actual_instance = JustWebsocketMessageGameGameDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into JustWebsocketMessageArrayGamePayoutEventDTO
        try:
            instance.actual_instance = JustWebsocketMessageArrayGamePayoutEventDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into JustWebsocketMessageGamePlayerActionDTO
        try:
            instance.actual_instance = JustWebsocketMessageGamePlayerActionDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into JustWebsocketMessageGameTurnStartEventDTO
        try:
            instance.actual_instance = JustWebsocketMessageGameTurnStartEventDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into JustWebsocketMessageGameChipExchangeDTO
        try:
            instance.actual_instance = JustWebsocketMessageGameChipExchangeDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into GameGameIdStateListenGet200Response with oneOf schemas: JustWebsocketMessageArrayGamePayoutEventDTO, JustWebsocketMessageGameChipExchangeDTO, JustWebsocketMessageGameGameDTO, JustWebsocketMessageGameHandStartEventDTO, JustWebsocketMessageGamePlayerActionDTO, JustWebsocketMessageGameRoundStartEventDTO, JustWebsocketMessageGameTurnStartEventDTO. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into GameGameIdStateListenGet200Response with oneOf schemas: JustWebsocketMessageArrayGamePayoutEventDTO, JustWebsocketMessageGameChipExchangeDTO, JustWebsocketMessageGameGameDTO, JustWebsocketMessageGameHandStartEventDTO, JustWebsocketMessageGamePlayerActionDTO, JustWebsocketMessageGameRoundStartEventDTO, JustWebsocketMessageGameTurnStartEventDTO. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], JustWebsocketMessageArrayGamePayoutEventDTO, JustWebsocketMessageGameChipExchangeDTO, JustWebsocketMessageGameGameDTO, JustWebsocketMessageGameHandStartEventDTO, JustWebsocketMessageGamePlayerActionDTO, JustWebsocketMessageGameRoundStartEventDTO, JustWebsocketMessageGameTurnStartEventDTO]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


