# coding: utf-8

"""
    BAHMS Poker Tournament

    # Error Format & Meaning  All response messages are in the format of: ```json {   \"message_type\": \"string\",   \"data\": {} } ```  All errors use the \"error\" message_type and have the data format of: ```json {   \"error_code\": int,   \"error\": \"string\" } ```   The \"error\" field is intended only as a human readable message and should not be depended on for branching or parsing in code. This field should be considered volatile within the api. The error_code field is stable and intended for client code to use within recovery operations. The error codes and their meanings are enumerated in the table below   |   Code | Name                  | Meaning                                       | | -----: | --------------------- | --------------------------------------------- | | `1000` | `Unknown` | A novel error...congrats.                | | `1001` | `TurnOrderViolation`     | Player action received for a player out of turn. | | `1002` | `InvalidActionType`   | Player action received with an intent that is not valid for the game state.                        | | `1003` | `NotEnoughChips`   | Player action received with a chip amount that cannot be covered by the players stack            | | `1004` | `InvalidBetAmount`    | Player action received with a bet amount that violates requirements i.e. incorrect amount for a blind, call, or a raise which is too low.                 |   

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class JustErrorCode(int, Enum):
    """
    JustErrorCode
    """

    """
    allowed enum values
    """
    SkillIssue = 67
    Unknown = 1000
    UserNotFound = 1001
    GameNotFound = 1002
    TokenMissing = 1003
    MalformedRequestBody = 1004
    TurnOrderViolation = 2000
    InvalidActionType = 2001
    NotEnoughChips = 2002
    InvalidBetAmount = 2003
    InvalidChipExchange = 2004
    ExpectedAnteAction = 2005
    GameAlreadyStarted = 2020
    GameIsFull = 2021
    PlayerAlreadyJoined = 2022
    GameIsPaused = 2023
    InvalidGameConfiguration = 2024
    HandAlreadyInProgress = 2025

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of JustErrorCode from a JSON string"""
        return cls(json.loads(json_str))


