# coding: utf-8

"""
    BAHMS Poker Tournament

    # Error Format & Meaning  All response messages are in the format of: ```json {   \"message_type\": \"string\",   \"data\": {} } ```  All errors use the \"error\" message_type and have the data format of: ```json {   \"error_code\": int,   \"error\": \"string\" } ```   The \"error\" field is intended only as a human readable message and should not be depended on for branching or parsing in code. This field should be considered volatile within the api. The error_code field is stable and intended for client code to use within recovery operations. The error codes and their meanings are enumerated in the table below   |   Code | Name                  | Meaning                                       | | -----: | --------------------- | --------------------------------------------- | | `1000` | `Unknown` | A novel error...congrats.                | | `1001` | `TurnOrderViolation`     | Player action received for a player out of turn. | | `1002` | `InvalidActionType`   | Player action received with an intent that is not valid for the game state.                        | | `1003` | `NotEnoughChips`   | Player action received with a chip amount that cannot be covered by the players stack            | | `1004` | `InvalidBetAmount`    | Player action received with a bet amount that violates requirements i.e. incorrect amount for a blind, call, or a raise which is too low.                 |   

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.game_new_game_config_dto import GameNewGameConfigDTO

class TestGameNewGameConfigDTO(unittest.TestCase):
    """GameNewGameConfigDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameNewGameConfigDTO:
        """Test GameNewGameConfigDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameNewGameConfigDTO`
        """
        model = GameNewGameConfigDTO()
        if include_optional:
            return GameNewGameConfigDTO(
                auto_starts_hands = True,
                big_blind = 56,
                bot_turn_timeout = 56,
                chip_denominations = [
                    56
                    ],
                player_count = 56,
                small_blind = 56,
                starting_chips = {
                    'key' : 56
                    }
            )
        else:
            return GameNewGameConfigDTO(
        )
        """

    def testGameNewGameConfigDTO(self):
        """Test GameNewGameConfigDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
