# coding: utf-8

"""
    BAHMS Poker Tournament

    # Error Format & Meaning  All response messages are in the format of: ```json {   \"message_type\": \"string\",   \"data\": {} } ```  All errors use the \"error\" message_type and have the data format of: ```json {   \"error_code\": int,   \"error\": \"string\" } ```   The \"error\" field is intended only as a human readable message and should not be depended on for branching or parsing in code. This field should be considered volatile within the api. The error_code field is stable and intended for client code to use within recovery operations. The error codes and their meanings are enumerated in the table below   |   Code | Name                  | Meaning                                       | | -----: | --------------------- | --------------------------------------------- | | `1000` | `Unknown` | A novel error...congrats.                | | `1001` | `TurnOrderViolation`     | Player action received for a player out of turn. | | `1002` | `InvalidActionType`   | Player action received with an intent that is not valid for the game state.                        | | `1003` | `NotEnoughChips`   | Player action received with a chip amount that cannot be covered by the players stack            | | `1004` | `InvalidBetAmount`    | Player action received with a bet amount that violates requirements i.e. incorrect amount for a blind, call, or a raise which is too low.                 |   

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.game_game_id_state_listen_get200_response import GameGameIdStateListenGet200Response

class TestGameGameIdStateListenGet200Response(unittest.TestCase):
    """GameGameIdStateListenGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameGameIdStateListenGet200Response:
        """Test GameGameIdStateListenGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameGameIdStateListenGet200Response`
        """
        model = GameGameIdStateListenGet200Response()
        if include_optional:
            return GameGameIdStateListenGet200Response(
                data = openapi_client.models.game/chip_exchange_dto.game.ChipExchangeDTO(
                    give = {
                        'key' : 56
                        }, 
                    receive = {
                        'key' : 56
                        }, 
                    user_id = '', ),
                event_type = '',
                id = 56,
                time_sent = ''
            )
        else:
            return GameGameIdStateListenGet200Response(
        )
        """

    def testGameGameIdStateListenGet200Response(self):
        """Test GameGameIdStateListenGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
