# coding: utf-8

"""
    BAHMS Poker Tournament

    # Error Format & Meaning  All response messages are in the format of: ```json {   \"message_type\": \"string\",   \"data\": {} } ```  All errors use the \"error\" message_type and have the data format of: ```json {   \"error_code\": int,   \"error\": \"string\" } ```   The \"error\" field is intended only as a human readable message and should not be depended on for branching or parsing in code. This field should be considered volatile within the api. The error_code field is stable and intended for client code to use within recovery operations. The error codes and their meanings are enumerated in the table below   |   Code | Name                  | Meaning                                       | | -----: | --------------------- | --------------------------------------------- | | `1000` | `Unknown` | A novel error...congrats.                | | `1001` | `TurnOrderViolation`     | Player action received for a player out of turn. | | `1002` | `InvalidActionType`   | Player action received with an intent that is not valid for the game state.                        | | `1003` | `NotEnoughChips`   | Player action received with a chip amount that cannot be covered by the players stack            | | `1004` | `InvalidBetAmount`    | Player action received with a bet amount that violates requirements i.e. incorrect amount for a blind, call, or a raise which is too low.                 |   

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_api import AdminApi


class TestAdminApi(unittest.IsolatedAsyncioTestCase):
    """AdminApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AdminApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_admin_game_game_id_status_post(self) -> None:
        """Test case for admin_game_game_id_status_post

        Update Game Status
        """
        pass

    async def test_admin_game_game_id_table_post(self) -> None:
        """Test case for admin_game_game_id_table_post

        Change Game Table
        """
        pass


if __name__ == '__main__':
    unittest.main()
