# coding: utf-8

"""
    BAHMS Poker Tournament

    # Error Format & Meaning  All response messages are in the format of: ```json {   \"message_type\": \"string\",   \"data\": {} } ```  All errors use the \"error\" message_type and have the data format of: ```json {   \"error_code\": int,   \"error\": \"string\" } ```   The \"error\" field is intended only as a human readable message and should not be depended on for branching or parsing in code. This field should be considered volatile within the api. The error_code field is stable and intended for client code to use within recovery operations. The error codes and their meanings are enumerated in the table below   |   Code | Name                  | Meaning                                       | | -----: | --------------------- | --------------------------------------------- | | `1000` | `Unknown` | A novel error...congrats.                | | `1001` | `TurnOrderViolation`     | Player action received for a player out of turn. | | `1002` | `InvalidActionType`   | Player action received with an intent that is not valid for the game state.                        | | `1003` | `NotEnoughChips`   | Player action received with a chip amount that cannot be covered by the players stack            | | `1004` | `InvalidBetAmount`    | Player action received with a bet amount that violates requirements i.e. incorrect amount for a blind, call, or a raise which is too low.                 |   

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class GameRoundType(str, Enum):
    """
    the type of round
    """

    """
    allowed enum values
    """
    round_type_unset = 'unset'
    round_type_setup = 'setup'
    round_type_pre_flop = 'pre_flop'
    round_type_flop = 'flop'
    round_type_turn = 'turn'
    round_type_river = 'river'
    round_type_completed = 'completed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GameRoundType from a JSON string"""
        return cls(json.loads(json_str))


