# coding: utf-8

"""
    BAHMS Poker Tournament

    # Error Format & Meaning  All response messages are in the format of: ```json {   \"message_type\": \"string\",   \"data\": {} } ```  All errors use the \"error\" message_type and have the data format of: ```json {   \"error_code\": int,   \"error\": \"string\" } ```   The \"error\" field is intended only as a human readable message and should not be depended on for branching or parsing in code. This field should be considered volatile within the api. The error_code field is stable and intended for client code to use within recovery operations. The error codes and their meanings are enumerated in the table below   |   Code | Name                  | Meaning                                       | | -----: | --------------------- | --------------------------------------------- | | `1000` | `Unknown` | A novel error...congrats.                | | `1001` | `TurnOrderViolation`     | Player action received for a player out of turn. | | `1002` | `InvalidActionType`   | Player action received with an intent that is not valid for the game state.                        | | `1003` | `NotEnoughChips`   | Player action received with a chip amount that cannot be covered by the players stack            | | `1004` | `InvalidBetAmount`    | Player action received with a bet amount that violates requirements i.e. incorrect amount for a blind, call, or a raise which is too low.                 |   

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from openapi_client.models.game_card_dto import GameCardDTO
from openapi_client.models.game_hand_dto import GameHandDTO
from openapi_client.models.game_player_dto import GamePlayerDTO
from openapi_client.models.game_round_dto import GameRoundDTO
from pydantic import BaseModel, ConfigDict, Field, StrictInt
from pydantic_core import to_jsonable_python
from typing_extensions import Self


class GameTableDTO(BaseModel):
    """
    the table
    """ # noqa: E501
    big_blind_position: Optional[StrictInt] = Field(default=None, description="the position of the big blind")
    button_position: Optional[StrictInt] = Field(default=None, description="the position of the button")
    current_hand: Optional[GameHandDTO] = None
    current_round: Optional[GameRoundDTO] = None
    players: Optional[List[GamePlayerDTO]] = Field(default=None, description="An array of players at the table")
    pot: Optional[Dict[str, StrictInt]] = Field(default=None, description="an optional mapping of chips that is required by some action types.")
    small_blind_position: Optional[StrictInt] = Field(default=None, description="the position of the small blind")
    street: Optional[List[GameCardDTO]] = Field(default=None, description="the cards that are on the street (community cards)")
    __properties: ClassVar[List[str]] = ["big_blind_position", "button_position", "current_hand", "current_round", "players", "pot", "small_blind_position", "street"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GameTableDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of current_hand
        if self.current_hand:
            _dict['current_hand'] = self.current_hand.to_dict()
        # override the default output from pydantic by calling `to_dict()` of current_round
        if self.current_round:
            _dict['current_round'] = self.current_round.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in players (list)
        _items = []
        if self.players:
            for _item_players in self.players:
                if _item_players:
                    _items.append(_item_players.to_dict())
            _dict['players'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in street (list)
        _items = []
        if self.street:
            for _item_street in self.street:
                if _item_street:
                    _items.append(_item_street.to_dict())
            _dict['street'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GameTableDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "big_blind_position": obj.get("big_blind_position"),
            "button_position": obj.get("button_position"),
            "current_hand": GameHandDTO.from_dict(obj["current_hand"]) if obj.get("current_hand") is not None else None,
            "current_round": GameRoundDTO.from_dict(obj["current_round"]) if obj.get("current_round") is not None else None,
            "players": [GamePlayerDTO.from_dict(_item) for _item in obj["players"]] if obj.get("players") is not None else None,
            "pot": obj.get("pot"),
            "small_blind_position": obj.get("small_blind_position"),
            "street": [GameCardDTO.from_dict(_item) for _item in obj["street"]] if obj.get("street") is not None else None
        })
        return _obj


