# coding: utf-8

"""
    BAHMS Poker Tournament

    # Error Format & Meaning  All response messages are in the format of: ```json {   \"message_type\": \"string\",   \"data\": {} } ```  All errors use the \"error\" message_type and have the data format of: ```json {   \"error_code\": int,   \"error\": \"string\" } ```   The \"error\" field is intended only as a human readable message and should not be depended on for branching or parsing in code. This field should be considered volatile within the api. The error_code field is stable and intended for client code to use within recovery operations. The error codes and their meanings are enumerated in the table below   |   Code | Name                  | Meaning                                       | | -----: | --------------------- | --------------------------------------------- | | `1000` | `Unknown` | A novel error...congrats.                | | `1001` | `TurnOrderViolation`     | Player action received for a player out of turn. | | `1002` | `InvalidActionType`   | Player action received with an intent that is not valid for the game state.                        | | `1003` | `NotEnoughChips`   | Player action received with a chip amount that cannot be covered by the players stack            | | `1004` | `InvalidBetAmount`    | Player action received with a bet amount that violates requirements i.e. incorrect amount for a blind, call, or a raise which is too low.                 |   

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from openapi_client.models.game_card_dto import GameCardDTO
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self


class GamePlayerDTO(BaseModel):
    """
    Detailed information about a registered user.
    """ # noqa: E501
    current_bet: Optional[Dict[str, StrictInt]] = Field(default=None, description="an optional mapping of chips that is required by some action types.")
    display_name: Optional[StrictStr] = Field(default=None, description="the users display name")
    hole: Optional[List[GameCardDTO]] = Field(default=None, description="the cards current held by this player. the cards are only visible to authorized users. TODO: make the prev statement true, also make an anon card")
    position: Optional[StrictInt] = Field(default=None, description="the players position at the table, starting with 0 being the first player sitting clockwise from the dealer")
    pot_contribution: Optional[StrictInt] = Field(default=None, description="the sum total the player has contributed to the pot, note that this does not include chips currently in CurrentBet")
    stack: Optional[Dict[str, StrictInt]] = Field(default=None, description="an optional mapping of chips that is required by some action types.")
    state: Optional[StrictStr] = Field(default=None, description="the players state")
    user_id: Optional[StrictStr] = Field(default=None, description="the is of the user")
    user_type: Optional[StrictStr] = Field(default=None, description="the type of user TODO: make this an enum")
    __properties: ClassVar[List[str]] = ["current_bet", "display_name", "hole", "position", "pot_contribution", "stack", "state", "user_id", "user_type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GamePlayerDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in hole (list)
        _items = []
        if self.hole:
            for _item_hole in self.hole:
                if _item_hole:
                    _items.append(_item_hole.to_dict())
            _dict['hole'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GamePlayerDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "current_bet": obj.get("current_bet"),
            "display_name": obj.get("display_name"),
            "hole": [GameCardDTO.from_dict(_item) for _item in obj["hole"]] if obj.get("hole") is not None else None,
            "position": obj.get("position"),
            "pot_contribution": obj.get("pot_contribution"),
            "stack": obj.get("stack"),
            "state": obj.get("state"),
            "user_id": obj.get("user_id"),
            "user_type": obj.get("user_type")
        })
        return _obj


